(require-extension fmt)
(use fmt)
(declare (uses parse))
(define (format-output hotkeys)
  (fmt #t (tabular
           (dsp (string-join (map car hotkeys) "\n")) " - " (dsp (string-join (map cadr hotkeys) "\n")))))
(define (sxhkd-default-config)
  (string-concatenate (list (get-environment-variable "HOME") "/.config/sxhkd/sxhkdrc")))
(define (process-hotkey hotkey)
  (let ((command (car hotkey))
        (documentation (cadr hotkey)))
    (cond
     ((and (list? command) (list? (car documentation))) (zip command (car documentation)))
     (#t (cartesian-product (bundle-list (list command documentation)))))))
(define (process-hotkeys hotkeys)
  (foldl append '() (map process-hotkey hotkeys)))
(define (run args)
  (format-output (process-hotkeys (parse-file (if (= (length args) 1)
                                                  (car args)
                                                  (sxhkd-default-config))))))
(run (command-line-arguments))
